config/routes.rb
Rails.application.routes.draw do

  resources :flats do
    resources :bookings, only: [:new, :create]
  end

  resources :bookings, only: [:index, :destroy, :show, :edit, :update] do
    member do
      patch '/confirm_booking', to: 'bookings#booking_status', as: :booking_status
      patch '/cancel_booking', to: 'bookings#cancel_booking', as: :cancelled_booking
      patch '/mark_as_paid', to: 'bookings#mark_as_paid', as: :mark_as_paid

    end
  end

  get '/requests', to: 'bookings#requests'
  get '/terms', to: 'pages#terms'

  resources :suggestions, only: [:new, :create, :index, :edit, :update, :destroy]
  resources :orders, only: [:show, :create] do
    resources :payments, only: [:new, :create]
  end

  mount Attachinary::Engine => "/attachinary"

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, :controllers => { registrations: 'registrations'}
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  scope '(:locale)', locale: /fr|en|it/ do
    root to: 'pages#home'
    resources :devise
  end
end

app/models/booking.rb
class Booking < ApplicationRecord
  after_create :send_admin_new_booking
  belongs_to :flat
  belongs_to :user
  has_one :order, dependent: :destroy

  validates :start_date, presence: true
  validates :end_date, presence: true

  monetize :price_cents

  # FRANCAIS
  def send_new_booking_mail_fr
    UserMailer.french_new_booking(self.user, self).deliver_now
  end

  def send_cancelled_booking_mail_fr
    UserMailer.french_cancelled_booking(self.user, self).deliver_now
  end
  # ENGLISH
  def send_new_booking_mail_en
    UserMailer.english_new_booking(self.user, self).deliver_now
  end

  def send_cancelled_booking_mail_en
    UserMailer.english_cancelled_booking(self.user, self).deliver_now
  end
  # ADMIN Mails
  def send_admin_payment_mail
    UserMailer.payment(self.user, self).deliver_now
  end
  private
  def send_admin_new_booking
    UserMailer.admin_new_booking(self.user, self).deliver_now
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :authenticate_admin!, only: [:requests, :booking_status, :edit, :destroy]

  def index
    @bookings = Booking.all.where(user: current_user).order(start_date: :asc)
  end

  def requests
    admin = User.all.where(admin: true)
    leport = Flat.all.where(title: "Le Port")
    laplage = Flat.all.where(title: "La Plage")

    @bookings = Booking.all.order(start_date: :asc)
    @recent = Booking.all.order(created_at: :desc).last(20)
    @users_bookings = Booking.all.order(start_date: :asc).where.not(user: admin)
    @bookings_leport = @bookings.where(flat: leport)
    @bookings_laplage = @bookings.where(flat: laplage)
    @confirmed = @bookings.where(status: "confirmed")
    @unconfirmed = @bookings.where(status: "unconfirmed")
    @unpaid = @users_bookings
    @cancelled = @bookings.where(status: "cancelled")
    @admin_bookings = Booking.all.order(start_date: :asc).where(user: admin)
  end

  def show
    @booking = Booking.find(params[:id])
    @order = @booking.order
  end

  def new
    @booking = Booking.new
  end

  def create
    @flat = Flat.find(params[:flat_id])
    @booking = Booking.new(booking_params)
    if (@booking.start_date != "" && @booking.end_date != "") && (@booking.start_date != @booking.end_date) && @booking.start_date.to_date < @booking.end_date.to_date
      @booking.user = current_user
      @booking.flat = @flat
      @booking.sku = "booking-#{@flat.title.delete(' ').downcase}"
      @booking.price_cents = total_price(@booking)
      @order  = Order.create!(booking_sku: @booking.sku, amount: @booking.price_cents, state: 'pending')
      @order.booking = @booking
      @order.save
      if @booking.save
        redirect_to booking_path(@booking)
      else
        redirect_to flat_path(@flat), alert: "Something went wrong, booking request cancelled"
      end
    else
      redirect_to flat_path(@flat), alert: "You need to select two different dates to book a flat"
    end
  end

  def booking_status
    @booking = Booking.find(params[:id])
    if @booking.status == "unconfirmed"
      @booking.status = "confirmed"
      @booking.save
      if I18n.locale == I18n.default_locale
        @booking.send_new_booking_mail_fr
      else
        @booking.send_new_booking_mail_en
      end
      redirect_to requests_path
    else
      redirect_to requests_path, alert: "Something went wrong, booking unconfirmed"
    end
  end

  def total_price(booking)
    start_d = Date.parse(booking.start_date)
    end_d = Date.parse(booking.end_date)

    multiplier = (end_d.cweek - start_d.cweek) - 1

    date = start_d
    total_price = booking_price(date)
    multiplier.times do
      date += 7
      total_price += booking_price(date)
    end
    return total_price
  end

  def booking_price(date)
    # Date format -> yyyy-mm-dd
    start_d = date

    case
    when start_d.month == 12 && start_d.day >= 23
      week = 500
    when (start_d.month == 11 && start_d.day >= 4) || (start_d.month == 12 && start_d.day >= 1)
      week = 350
    when (start_d.month == 9 && start_d.day >= 16) || (start_d.month >= 10 && start_d.day >= 1)
      week = 500
    when start_d.month == 9 && start_d.day >= 2
      week = 600
    when (start_d.month == 8 && start_d.day >= 19) || (start_d.month == 9 && start_d.day >= 1)
      week = 750
    when (start_d.month == 7 && start_d.day >= 15) || (start_d.month == 8 && start_d.day >= 1)
      week = 900
    when start_d.month == 7 && start_d.day >= 1
      week = 750
    when start_d.month == 6 && start_d.day >= 10
      week = 600
    when (start_d.month == 4 && start_d.day >= 1) || (start_d.month == 5 && start_d.day >= 1) || (start_d.month == 6 && start_d.day >= 3)
      week = 500
    when (start_d.month == 1 && start_d.day >= 7) || (start_d.month == 2 && start_d.day >= 1) || (start_d.month == 3 && start_d.day >= 1)
      week = 350
    when (start_d.month == 12 && start_d.day >= 31) || (start_d.month == 1 && start_d.day >= 1)
      week = 500
    end
  end

  def edit
    @booking = Booking.find(params[:id])
  end

  def update
    @booking = Booking.find(params[:id])
    @order = @booking.order
    if @booking.update(booking_params)
      @order.amount = @booking.price_cents
      @order.save
      redirect_to requests_path, notice: "Booking successfully updated"
    else
      redirect_to requests_path, alert: "Something went wrong"
    end
  end

  def cancel_booking
    @booking = Booking.find(params[:id])
    @booking.status = "cancelled"
    if @booking.save
      if I18n.locale == I18n.default_locale
        @booking.send_cancelled_booking_mail_fr
      else
        @booking.send_cancelled_booking_mail_en
      end
      redirect_to requests_path, notice: "Booking successfully cancelled"
    else
      redirect_to requests_path, alert: "Something went wrong, booking not cancelled"
    end
  end

  def destroy
    @booking = Booking.find(params[:id])
    if @booking.destroy
      redirect_to requests_path, notice: "Booking successfully deleted"
    else
      redirect_to requests_path, alert: "Something went wrong!"
    end
  end

  def mark_as_paid
    @booking = Booking.find(params[:id])
    order = @booking.order
    if order.update(state: 'paid')
      redirect_to requests_path
    else
      redirect_to requests_path, alert: "Something went wrong, booking not cancelled"
    end
  end

  def mark_as_unpaid
    @order.update(state: 'pending')
  end

  private

  def booking_params
    params.require(:booking).permit(:flat_id, :price_cents, :start_date, :end_date, :status, :message, :admin_comment)
  end

  def order_params
    params.require(:order).permit(:state)
  end
end

app/helpers/booking_helper.rb
module BookingHelper
end

app/views/bookings/_booking-card.html.erb
<div class="product">
  <div class='product-upvote'>
    <div><i class="fa fa-calendar"></i></div>
    <div class='product-count'><%= booking.start_date %></div>
  </div>
  <% if booking.flat.banner_photo %>
  <%= cl_image_tag booking.flat.banner_photo.path, class: "product-image hidden-xs" %>
  <% else %>
  <%= image_tag "background.jpg", class: "product-image hidden-xs" %>
  <% end %>
  <div class='product-body'>
    <p><%= booking.flat.title %></p>
    <p><%= booking.user.first_name %> <%= booking.user.last_name %></p>
    <p><%= booking.user.email %></p>
    <p><%= booking.message %></p>
    <p><%= l(booking.start_date.to_date) %> - <%= l(booking.end_date.to_date) %></p>
    <p><%= humanized_money_with_symbol(booking.price_cents) %></p>
    <% if booking.order.state == "pending"%>
    <p><i class="fa fa-exclamation-triangle" aria-hidden="true"></i> <%= t("booking.not_paid") %></p>
    <% elsif booking.order.state == "paid"%>
    <p><i class="fa fa-check-circle-o" aria-hidden="true"></i> <%= t("booking.paid") %></p>
    <% end %>
  </div>
  <ul class="list-inline product-controls">
    <%= link_to booking_path(booking) do %>
    <li><i class="fa fa-info-circle"></i></li>
    <% end %>
  </ul>
</div>

app/views/bookings/_booking-confirmed.html.erb
<div class="product">
  <div class='product-upvote'>
    <div><i class="fa fa-calendar"></i></div>
    <div class='product-count'><%= booking.start_date %></div>
  </div>
  <% if booking.flat.banner_photo %>
  <%= cl_image_tag booking.flat.banner_photo.path, class: "product-image hidden-xs" %>
  <% else %>
  <%= image_tag "background.jpg", class: "product-image hidden-xs" %>
  <% end %>
  <div class='product-body'>
    <% if booking.user.admin == true %>
    <p><%= booking.flat.title %></p>
    <p><%= booking.message %></p>
    <p><%= l(booking.start_date.to_date) %> - <%= l(booking.end_date.to_date) %></p>
    <% else %>
    <p><%= booking.flat.title %></p>
    <p><%= booking.user.first_name %> <%= booking.user.last_name %></p>
    <p><%= booking.user.phone %></p>
    <p><%= booking.user.email %></p>
    <p><%= booking.message %></p>
    <p><%= l(booking.start_date.to_date) %> - <%= l(booking.end_date.to_date) %></p>
    <p><%= humanized_money_with_symbol(booking.price_cents) %></p>
    <% end %>
    <% if booking.user.admin == true %>
    <p><i class="fa fa-user" aria-hidden="true"></i> ADMIN BOOKING</p>
    <% elsif booking.order.state == "pending"%>
    <p><i class="fa fa-exclamation-triangle" aria-hidden="true"></i> <%= t("booking.not_paid") %></p>
    <% elsif booking.order.state == "paid"%>
    <p><i class="fa fa-check-circle-o" aria-hidden="true"></i> <%= t("booking.paid") %></p>
    <% end %>
  </div>
  <div class="request-buttons full-width-controls">
    <% if booking.status == "confirmed" && booking.order.state == "pending" || booking.user.admin == true && booking.status != "cancelled" %>
    <%= link_to 'Edit', edit_booking_path(booking), class: "btn btn-info btn-xs" %>
    <%= link_to 'Cancel', cancelled_booking_booking_path(booking), data: { confirm: 'Cancel?' }, method: :patch, class: "btn btn-danger btn-xs" %>
    <%= link_to "User", booking_path(booking), class: "btn btn-success btn-xs" %>
    <% if booking.order.state == "pending" %>
    <%= link_to "Paid?", mark_as_paid_booking_path(booking), method: :patch, class: "btn btn-default btn-xs", data: { confirm: 'Mark as paid?' } %>
    <% end %>
    <% elsif booking.status == 'cancelled' %>
    <%= link_to 'Delete', booking_path(booking), data: { confirm: 'Delete?' }, method: :delete, class: "btn btn-danger btn-xs" %>
    <% else %>
    <%= link_to 'Edit', edit_booking_path(booking), class: "btn btn-info btn-xs" %>
    <% end %>
  </div>
</div>

app/views/bookings/_booking-request-card.html.erb
<div class="product product-bordered">
  <div class='product-upvote'>
    <div><i class="fa fa-calendar"></i></div>
    <div class='product-count'><%= l(booking.start_date.to_date) %></div>
  </div>
  <% if booking.flat.banner_photo %>
  <%= cl_image_tag booking.flat.banner_photo.path, class: "product-image hidden-xs" %>
  <% else %>
  <%= image_tag "background.jpg", class: "product-image hidden-xs" %>
  <% end %>
  <div class='product-body'>
    <h4><%= booking.flat.title %></h4>
    <div class="product-body-user">
      <p><%= booking.user.first_name %> <%= booking.user.last_name %></p>
      <p><%= booking.user.phone %></p>
      <p><%= booking.user.email %></p>
    </div>
    <span><%= booking.message %></span>
    <p><%= l(booking.start_date.to_date) %> - <%= l(booking.end_date.to_date) %></p>
    <h4><%= humanized_money_with_symbol(booking.price_cents) %></h4>
    <% if booking.admin_comment && booking.admin_comment != ""%>
    <p><strong>Message au locataire:</strong> <%= booking.admin_comment %></p>
    <% end %>
  </div>
  <div class="request-buttons full-width-controls">
    <%= link_to 'Confirm', booking_status_booking_path(booking), data: { confirm: 'Confirm?' }, method: :patch, class: "btn btn-primary btn-xs" %>
    <%= link_to 'Edit', edit_booking_path(booking), class: "btn btn-info btn-xs" %>
    <%= link_to 'Cancel', cancelled_booking_booking_path(booking), data: { confirm: 'Cancel?' }, method: :patch, class: "btn btn-danger btn-xs" %>
  </div>
</div>

app/views/bookings/_terms.html.erb
<div class="terms">
<h2><%= t("terms.title") %></h2>
  <h3><%= t("terms.general_title") %></h3>
  <p><%= t("terms.general_content1") %></p>
  <ul>
    <li><%= t("terms.general_content1_list1") %></li>
    <li><%= t("terms.general_content1_list2") %></li>
    <li><%= t("terms.general_content1_list3") %></li>
    <li><%= t("terms.general_content1_list4") %></li>
    <li><%= t("terms.general_content1_list5") %></li>
  </ul>
  <h3><%= t("terms.deposit_title") %></h3>
  <p><%= t("terms.deposit_content1") %></p>
  <p><%= t("terms.deposit_content2") %></p>
  <h3><%= t("terms.inventory_title") %></h3>
  <p><%= t("terms.inventory_content1") %></p>
  <p><%= t("terms.inventory_content2") %></p>
  <ul>
    <li><%= t("terms.inventory_content2_list1") %></li>
    <li><%= t("terms.inventory_content2_list2") %></li>
  </ul>
  <p><%= t("terms.inventory_content3") %></p>
  <h3><%= t("terms.fee_title") %></h3>
  <p><%= t("terms.fee_content1") %></p>
</div>

app/views/bookings/edit.html.erb
<div class="container booking-container">
  <h2>Edit booking of <%= @booking.user.first_name %> <%= @booking.user.last_name %> (<%= l(@booking.start_date.to_date) %> - <%= l(@booking.end_date.to_date) %>)</h2>
  <%= simple_form_for @booking do |f| %>
  <%= f.association :flat %>
  <div class="form-inline">
    <%= f.input :price_cents, as: :integer, label: "Price" %>
  </div>
  <p><strong>Dates</strong></p>
  <div class="input-daterange input-group" id="datepicker">
    <input required name="booking[start_date]" type="text" class='datepicker input-sm form-control from' placeholder="From">
    <span class="input-group-addon">to</span>
    <input required name="booking[end_date]" type="text" class='datepicker input-sm form-control until' placeholder="Until">
  </div>

  <%= f.input :admin_comment, as: :text, label: "Commentaire (inclut dans le PS du mail de confirmation)"%>
  <%= f.button :submit, class: "btn btn-primary" %>
  <% end %>
  <%= link_to 'Delete', booking_path(@booking), data: { confirm: 'Delete?' }, method: :delete, class: "btn btn-danger btn-xs" %>
</div>

<%= content_for(:after_js) do %>
<script type="text/javascript">

  $('.datepicker').datepicker({
    autoclose: true,
    format: "yyyy-mm-dd",
    daysOfWeekDisabled: "0,1,2,3,4,5",
    daysOfWeekHighlighted: "6",
    todayHighlight: true
  });
  var start = new Date("<%= @booking.start_date.to_date %>")
  var end = new Date ("<%= @booking.end_date.to_date %>")
  $(".from").datepicker('setDate', start);
  $(".until").datepicker('setDate', end);

</script>
<% end %>

app/views/bookings/index.html.erb
<div class="container-fluid booking-container" style="background-color: aliceblue;">
  <% if @bookings.count != 0 %>
  <% @bookings.each do |booking| %>
  <div class="product">
    <div class='product-upvote'>
      <div><i class="fa fa-calendar"></i></div>
      <div class='product-count'><%= l(booking.start_date.to_date) %></div>
    </div>
    <% if booking.flat.banner_photo %>
    <%= cl_image_tag booking.flat.banner_photo.path, class: "product-image hidden-xs" %>
    <% else %>
    <%= image_tag "background.jpg", class: "product-image hidden-xs" %>
    <% end %>
    <div class='product-body'>
      <h3><%= booking.flat.title %></h3>
      <% if booking.status == "unconfirmed" %>
      <p><%= t("booking.unconfirmed") %></p>
      <% elsif booking.status == "confirmed" && booking.order.state == "pending"%>
      <p><%= t("booking.confirmed") %> | <i class="fa fa-exclamation-triangle" aria-hidden="true"></i>
 <%= t("booking.not_paid") %></p>
      <% elsif booking.status == "confirmed" && booking.order.state == "paid"%>
      <p><%= t("booking.confirmed") %> | <i class="fa fa-check-circle-o" aria-hidden="true"></i>
 <%= t("booking.paid") %></p>
      <% elsif booking.status == "cancelled" %>
      <p><%= t("booking.cancelled") %></p>
      <% end %>
      <p><%= t("booking.amount") %>: <%= humanized_money_with_symbol(booking.price_cents) %></p>
      <p><%= (booking.end_date.to_date - booking.start_date.to_date).to_i %> <%= t("booking.nights") %></p>
    </div>
    <div class="list-inline booking-controls hidden-sm hidden-xs">
      <%= link_to booking_path(booking), class: "btn btn-primary" do %>
      <i class="fa fa-info-circle"></i> <%= t("booking.info") %>
      <% end %>
    </div>
  </div>
  <% end %>
  <% else %>
  <div class="text-center no-bookings">
    <h2><%= t("booking.no_booking_request") %></h2>
    <%= link_to t("home_banner.button"), flats_path, class: "btn btn-primary" %>
  </div>
  <% end %>
</div>

app/views/bookings/requests.html.erb
<div class="container booking-container">

  <!-- Nav tabs -->
  <ul class="nav nav-tabs" role="tablist">
    <li role="presentation" class="active"><a href="#bookings" aria-controls="bookings" role="tab" data-toggle="tab">Bookings requests</a></li>
    <li role="presentation"><a href="#recent" aria-controls="recent" role="tab" data-toggle="tab">Recent requests</a></li>
    <li role="presentation"><a href="#leport" aria-controls="leport" role="tab" data-toggle="tab">Le Port</a></li>
    <li role="presentation"><a href="#laplage" aria-controls="laplage" role="tab" data-toggle="tab">La Plage</a></li>
    <li role="presentation"><a href="#all-confirmed" aria-controls="all-confirmed" role="tab" data-toggle="tab">All confirmed</a></li>
    <li role="presentation"><a href="#all-cancelled" aria-controls="all-cancelled" role="tab" data-toggle="tab">All cancelled</a></li>
    <li role="presentation"><a href="#all-unpaid" aria-controls="all-unpaid" role="tab" data-toggle="tab">All unpaid</a></li>
    <li role="presentation"><a href="#all-users" aria-controls="all-users" role="tab" data-toggle="tab">USERS</a></li>
    <li role="presentation"><a href="#all-admin" aria-controls="all-admin" role="tab" data-toggle="tab">ADMIN</a></li>

  </ul>

  <!-- Tab panes -->
  <div class="tab-content">
    <div role="tabpanel" class="tab-pane active" id="bookings">
      <% @unconfirmed.each do |booking| %>
      <%= render "booking-request-card", booking: booking %>
      <% end %>
    </div>

    <div role="tabpanel" class="tab-pane" id="recent">
      <% @recent.each do |booking| %>
      <%= render "booking-confirmed", booking: booking %>
      <% end %>
    </div>

    <div role="tabpanel" class="tab-pane" id="leport">
      <h3>Requests</h3>
      <% @bookings_leport.where(status: "unconfirmed").each do |booking| %>
      <%= render "booking-request-card", booking: booking %>
      <% end %>
      <h3>Confirmed</h3>
      <% @bookings_leport.where(status: "confirmed").each do |booking| %>
      <%= render "booking-confirmed", booking: booking %>
      <% end %>
      <h3>Cancelled</h3>
      <% @bookings_leport.where(status: "cancelled").each do |booking| %>
      <%= render "booking-confirmed", booking: booking %>
      <% end %>
    </div>

    <div role="tabpanel" class="tab-pane" id="laplage">
      <h3>Requests</h3>
      <% @bookings_laplage.where(status: "unconfirmed").each do |booking| %>
      <%= render "booking-request-card", booking: booking %>
      <% end %>
      <h3>Confirmed</h3>
      <% @bookings_laplage.where(status: "confirmed").each do |booking| %>
      <%= render "booking-confirmed", booking: booking %>
      <% end %>
      <h3>Cancelled</h3>
      <% @bookings_laplage.where(status: "cancelled").each do |booking| %>
      <%= render "booking-confirmed", booking: booking %>
      <% end %>
    </div>

    <div role="tabpanel" class="tab-pane" id="all-confirmed">
      <% @confirmed.each do |booking| %>
      <%= render "booking-confirmed", booking: booking %>
      <% end %>
    </div>

    <div role="tabpanel" class="tab-pane" id="all-cancelled">
      <% @cancelled.each do |booking| %>
      <%= render "booking-confirmed", booking: booking %>
      <% end %>
    </div>
    <div role="tabpanel" class="tab-pane" id="all-unpaid">
      <% @unpaid.each do |booking| %>
      <% if booking.order.state == "pending" %>
      <%= render "booking-confirmed", booking: booking %>
      <% end %>
      <% end %>
    </div>

    <div role="tabpanel" class="tab-pane" id="all-users">
      <div class="row">
        <div class="col-xs-6 column-request">
          <h4>Le Port</h4>
          <% @users_bookings.each do |booking| %>
          <% if booking.flat.title == "Le Port" %>
          <%= render "booking-confirmed", booking: booking %>
          <% end %>
          <% end %>
        </div>
        <div class="col-xs-6 column-request">
          <h4>La Plage</h4>
          <% @users_bookings.each do |booking| %>
          <% if booking.flat.title == "La Plage" %>
          <%= render "booking-confirmed", booking: booking %>
          <% end %>
          <% end %>
        </div>
      </div>
    </div>

    <div role="tabpanel" class="tab-pane" id="all-admin">
      <div class="row">
        <div class="col-xs-6 column-request">
          <h4>Le Port</h4>
          <% @admin_bookings.each do |booking| %>
          <% if booking.flat.title == "Le Port" %>
          <%= render "booking-confirmed", booking: booking %>
          <% end %>
          <% end %>
        </div>
        <div class="col-xs-6 column-request">
          <h4>La Plage</h4>
          <% @admin_bookings.each do |booking| %>
          <% if booking.flat.title == "La Plage" %>
          <%= render "booking-confirmed", booking: booking %>
          <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/bookings/show.html.erb
<div class="container booking-container">
  <h2><%= t("booking.your_booking") %></h2>
  <div class="booking">
    <% if @booking.flat.banner_photo %>
    <%= cl_image_tag @booking.flat.banner_photo.path, class: "booking-image" %>
    <% else %>
    <%= image_tag "background.jpg", class: "booking-image" %>
    <% end %>
    <div class='booking-body'>
      <h3><%= @booking.flat.title %></h3>
      <p><%= @booking.message %></p>
      <% if @booking.status == "unconfirmed" %>
      <p><%= t("booking.unconfirmed") %></p>
      <% elsif @booking.status == "confirmed" && @booking.order.state == "pending"%>
      <p><%= t("booking.confirmed") %> | <i class="fa fa-exclamation-triangle" aria-hidden="true"></i>
       <%= t("booking.not_paid") %></p>
       <% elsif @booking.status == "confirmed" && @booking.order.state == "paid"%>
       <p><%= t("booking.confirmed") %> | <i class="fa fa-check-circle-o" aria-hidden="true"></i>
         <%= t("booking.paid") %></p>
         <% elsif @booking.status == "cancelled" %>
         <p><%= t("booking.cancelled") %></p>
         <% end %>
         <% if @booking.order.state == "pending" %>
         <h2><%= t("booking.amount") %>: <%= humanized_money_with_symbol(@booking.price_cents) %></h2>
         <% else %>
         <h2><%= t("booking.amount") %>: <%= humanized_money_with_symbol(@booking.order.amount) %></h2>
         <% end %>
         <h2><i class="fa fa-calendar"></i> <%= l(@booking.start_date.to_date) %> <%= t("booking.to") %> <%= l(@booking.end_date.to_date) %></h2>
         <h2><%= (@booking.end_date.to_date - @booking.start_date.to_date).to_i %> <%= t("booking.nights") %></h2>
       </div>
       <div class="booking-controls full-width-controls">
         <%= link_to t("booking.flat"), flat_path(@booking.flat), class: "btn btn-primary" %>
         <a href="mailto:francois@cap-vauban.com" class="btn btn-success"><%= t("shared.email_us") %></a>
         <% if @booking.status == "confirmed" && @booking.order.state == "pending"%>
         <%= form_tag order_payments_path(@order) do %>
         <% if flash[:error].present? %>
         <div id="error_explanation">
          <p><%= flash[:error] %></p>
        </div>
        <% end %>

        <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
        data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
        data-name="<%= t('booking.payment_title') %>"
        data-description="<%= l(@booking.start_date.to_date) %> <%= t("booking.to") %> <%= l(@booking.end_date.to_date) %>"
        data-currency="<%= @order.amount.currency %>"
        data-locale="auto"
        data-image="<%= image_path("favicon.png") %>">
      </script>
      <p>
       <input class="coupon" type="text" name="couponCode" id="couponCode" placeholder="Coupon">
     </p>
     <div class="terms-info">
       <p><%= t("terms.info") %> <a href="#" data-toggle="modal" data-target="#myModal"><%= t("terms.title") %></a></p>
     </div>
     <% end %>
     <% elsif @booking.status == "confirmed" && @booking.order.state == "paid"%>
     <button class="payment-recieved-button" disabled><i class="fa fa-check-circle-o" aria-hidden="true"></i> <%= t("booking.paid") %></button>
     <% end %>
   </div>
 </div>
</div>

<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog terms-modal" role="document">
    <div class="modal-content">
      <div class="modal-body">
        <%= render "terms" %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>