config/routes.rb
Rails.application.routes.draw do

  resources :flats do
    resources :bookings, only: [:new, :create]
  end

  resources :bookings, only: [:index, :destroy, :show, :edit, :update] do
    member do
      patch '/confirm_booking', to: 'bookings#booking_status', as: :booking_status
      patch '/cancel_booking', to: 'bookings#cancel_booking', as: :cancelled_booking
      patch '/mark_as_paid', to: 'bookings#mark_as_paid', as: :mark_as_paid

    end
  end

  get '/requests', to: 'bookings#requests'
  get '/terms', to: 'pages#terms'

  resources :suggestions, only: [:new, :create, :index, :edit, :update, :destroy]
  resources :orders, only: [:show, :create] do
    resources :payments, only: [:new, :create]
  end

  mount Attachinary::Engine => "/attachinary"

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, :controllers => { registrations: 'registrations'}
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  scope '(:locale)', locale: /fr|en|it/ do
    root to: 'pages#home'
    resources :devise
  end
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer-container">

  <div class="footer-left text-center hidden-xs">
  <h4><%= t("shared.about_us") %></h4>
    <ul class="list-inline">
      <li><%= link_to flats_path do %>
      <i class="fa fa-home" aria-hidden="true"></i><%= t("shared.our_flats") %>
        <% end %>
      </li>
      <li><%= link_to suggestions_path do %>
      <i class="fa fa-list" aria-hidden="true"></i><%= t("shared.our_suggestions") %>
        <% end %>
      </li>
    </ul>
  </div>
  <div class="footer-middle text-center">
    <h4><%= t("shared.contact") %></h4>
    <ul>
      <li><a href="mailto:francois@cap-vauban.com"><i class="fa fa-envelope" aria-hidden="true"></i><%= t("shared.email_us") %></a></li>
    </ul>
  </div>
  <div class='footer-right text-center'>
    <h4><%= t("shared.developer") %></h4>
    <ul class="list-inline">
      <li><a href="mailto:arthur.littmann@gmail.com"><i class="fa fa-code" aria-hidden="true"></i><%= t("shared.email_dev") %></a></li>
    </ul>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
  <%= image_tag "logoblack.png" %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">
    <% if user_signed_in? && current_user.admin %>
    <div class="badge-container">
      <%= link_to t("shared.booking_admin"), requests_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <div class="badge badge-blue"><%= Booking.all.where(status: "unconfirmed").count %></div>
    </div>
    <% end %>

    <!-- Different navigation if login or not -->
    <% if user_signed_in? %>

    <%= link_to t("shared.flats"), flats_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <%= link_to t("shared.bookings"), bookings_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <%= link_to t("devise.sign_out"), destroy_user_session_path, method: :delete, class: "navbar-wagon-item navbar-wagon-link-danger" %>


    <% else %>

    <!-- Login text link -->
    <%= link_to t("devise.sign_in"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <%= link_to t("devise.sign_up"), new_user_registration_path, class: "navbar-wagon-item navbar-wagon-link" %>


    <% end %>
    <% if I18n.locale == I18n.default_locale %>
    <%= link_to image_tag("english.png"), { :locale=>'en' }, class: "i18n-set-locale" %>
    <% else %>
    <%= link_to image_tag("french.png"), { :locale=>'fr' }, class: "i18n-set-locale" %>
    <%end%>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <% if user_signed_in? %>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <% if user_signed_in? && current_user.admin %>
        <li>
          <%= link_to t("shared.booking_admin"), requests_path, class: "navbar-wagon-item navbar-wagon-link" %>
        </li>
        <% end %>
        <li><%= link_to flats_path, class: "navbar-wagon-item navbar-wagon-link" do %>
          <i class="fa fa-home"></i> <%= t("shared.flats") %>
          <% end %>
        </li>
        <li><%= link_to bookings_path, class: "navbar-wagon-item navbar-wagon-link" do %>
          <i class="fa fa-calendar"></i> <%= t("shared.bookings") %>
          <% end %>
        </li>
        <li><%= link_to destroy_user_session_path, method: :delete do %>
          <i class="fa fa-sign-out"></i>  <%= t("devise.sign_out") %>
          <% end %>
        </li>
        <li>
          <% if I18n.locale == I18n.default_locale %>
          <%= link_to "English website", { :locale=>'en' }, class: "navbar-wagon-item navbar-wagon-link" %>
          <% else %>
          <%= link_to "Site Français", { :locale=>'fr' }, class: "navbar-wagon-item navbar-wagon-link" %>
          <%end%>
        </li>
      </ul>
      <% else %>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><%= link_to t("devise.sign_in"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %></li>
        <li><%= link_to t("devise.sign_up"), new_user_registration_path, class: "navbar-wagon-item navbar-wagon-link" %></li>
        <li>
          <% if I18n.locale == I18n.default_locale %>
          <%= link_to "English website", { :locale=>'en' }, class: "navbar-wagon-item navbar-wagon-link" %>
          <% else %>
          <%= link_to "Site Français", { :locale=>'fr' }, class: "navbar-wagon-item navbar-wagon-link" %>
          <%end%>
        </li>
      </ul>
      <% end %>
    </div>

  </div>

</div>