config/routes.rb
Rails.application.routes.draw do

  resources :flats do
    resources :bookings, only: [:new, :create]
  end

  resources :bookings, only: [:index, :destroy, :show, :edit, :update] do
    member do
      patch '/confirm_booking', to: 'bookings#booking_status', as: :booking_status
      patch '/cancel_booking', to: 'bookings#cancel_booking', as: :cancelled_booking
      patch '/mark_as_paid', to: 'bookings#mark_as_paid', as: :mark_as_paid

    end
  end

  get '/requests', to: 'bookings#requests'
  get '/terms', to: 'pages#terms'

  resources :suggestions, only: [:new, :create, :index, :edit, :update, :destroy]
  resources :orders, only: [:show, :create] do
    resources :payments, only: [:new, :create]
  end

  mount Attachinary::Engine => "/attachinary"

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, :controllers => { registrations: 'registrations'}
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  scope '(:locale)', locale: /fr|en|it/ do
    root to: 'pages#home'
    resources :devise
  end
end

app/models/suggestion.rb
class Suggestion < ApplicationRecord
  has_attachment :photo

  geocoded_by :address
  after_validation :geocode, if: :address_changed?

  validates :title, presence: true
  validates :content, presence: true
  validates :content_english, presence: true
  validates :content_italian, presence: true
  validates :address, presence: true
end

app/controllers/suggestions_controller.rb
class SuggestionsController < ApplicationController
  before_action :authenticate_admin!, except: [:index]

  def new
    @suggestion = Suggestion.new
  end

  def create
    @suggestion = Suggestion.new(suggestion_params)
    if @suggestion.save
      redirect_to suggestions_path
    else
      render :new, alert: "Something went wrong!"
    end
  end

  def index
    @suggestions = Suggestion.all
  end

  def edit
    @suggestion = Suggestion.find(params[:id])
  end

  def update
    @suggestion = Suggestion.find(params[:id])
    if @suggestion.update(suggestion_params)
      redirect_to suggestions_path, notice: 'Suggestion mise a jour'
    else
      render :edit
    end
  end

  def destroy
    @suggestion = Suggestion.find(params[:id])
    if @suggestion.destroy
      redirect_to suggestions_path
    else
      redirect_to suggestions_path, alert: "Something went wrong!"
    end
  end

  private

  def suggestion_params
    params.require(:suggestion).permit(:title, :content, :content_english, :content_italian, :address, :link, :photo)
  end
end

app/helpers/suggestion_helper.rb
module SuggestionHelper
end

app/views/suggestions/edit.html.erb
<div class="container">
  <%= simple_form_for @suggestion do |f| %>
  <%= f.input :title %>
  <%= f.input :content %>
  <%= f.input :content_english %>
  <%= f.input :content_italian %>
  <%= f.input :address %>
  <%= f.input :link %>
  <%= f.input :photo, as: :attachinary %>
  <%= f.button :submit %>
  <% end %>
</div>

app/views/suggestions/index.html.erb
<div class="container-fluid booking-container" style="background-color: aliceblue;">
  <div class="row">
    <div class="text-center">
      <h2><%= t("suggestions.phrase") %></h2>
    </div>
    <div class="col-xs-12 col-md-7 suggestions-container">
      <% @suggestions.each do |suggestion| %>
      <div class="product">
        <% if suggestion.photo %>
        <%= cl_image_tag suggestion.photo.path, class: "product-image hidden-xs" %>
        <% else %>
        <%= image_tag "background.jpg", class: "product-image hidden-xs" %>
        <% end %>
        <div class='product-body'>
          <h3><%= suggestion.title %></h3>
          <% if I18n.locale == I18n.default_locale %>
          <p><%= suggestion.content %></p>
          <% else %>
          <p><%= suggestion.content_english %></p>
          <%end%>
          <p class="product-address"><i class="fa fa-map-marker"></i> <%= suggestion.address %></p>
        </div>
        <ul class="list-inline product-controls hidden-sm hidden-xs">
          <% if user_signed_in? && current_user.admin %>
          <li>
            <%= link_to edit_suggestion_path(suggestion) do %>
            <i class="fa fa-wrench"></i>
            <% end %>
          </li>
          <li>
            <%= link_to suggestion_path(suggestion), method: :delete, data: { confirm: 'Are you sure?' } do %>
            <i class="fa fa-trash"></i>
            <% end %>
          </li>
          <% end %>
          <% if suggestion.link %>
          <li><a href="<%= suggestion.link %>" target="blank"><i class="fa fa-info-circle"></i></a></li>
          <% end %>
        </ul>
      </div>
      <% end %>
      <% if user_signed_in? && current_user.admin %>
      <%= link_to "New suggestion", new_suggestion_path, class: "btn btn-primary" %>
      <% else %>
      <a href="mailto:francois@cap-vauban.com" class="btn btn-primary"><%= t("suggestions.proposition") %></a>
      <% end %>
    </div>
    <div class="col-xs-12 col-md-5">
      <div id="map" class="suggestion-map" class="hidden-xs"></div>
    </div>
  </div>
</div>

<%= content_for(:after_js) do %>
<script type="text/javascript">

  $(document).ready(function(){
    var styles = [{"featureType":"water","stylers":[{"saturation":43},{"lightness":-11},{"hue":"#0088ff"}]},{"featureType":"road","elementType":"geometry.fill","stylers":[{"hue":"#ff0000"},{"saturation":-100},{"lightness":99}]},{"featureType":"road","elementType":"geometry.stroke","stylers":[{"color":"#808080"},{"lightness":54}]},{"featureType":"landscape.man_made","elementType":"geometry.fill","stylers":[{"color":"#ece2d9"}]},{"featureType":"poi.park","elementType":"geometry.fill","stylers":[{"color":"#ccdca1"}]},{"featureType":"road","elementType":"labels.text.fill","stylers":[{"color":"#767676"}]},{"featureType":"road","elementType":"labels.text.stroke","stylers":[{"color":"#ffffff"}]},{"featureType":"poi","stylers":[{"visibility":"off"}]},{"featureType":"landscape.natural","elementType":"geometry.fill","stylers":[{"visibility":"on"},{"color":"#b8cb93"}]},{"featureType":"poi.park","stylers":[{"visibility":"on"}]},{"featureType":"poi.sports_complex","stylers":[{"visibility":"on"}]},{"featureType":"poi.medical","stylers":[{"visibility":"on"}]},{"featureType":"poi.business","stylers":[{"visibility":"simplified"}]}];

    var handler = Gmaps.build('Google', { markers: { clusterer: undefined }});
    handler.buildMap({ internal: { id: 'map' }, provider: { scrollwheel: false, zoomControl: false, styles: styles } }, function(){
     markers = handler.addMarkers([
      <% @suggestions.each do |suggestion| %>
      {
        "lat": <%= suggestion.latitude %>,
        "lng": <%= suggestion.longitude %>,
        "infowindow": "<h4><%= suggestion.title %></h4>"
      },
      <% end %>
      ]);
     handler.bounds.extendWith(markers);
     handler.fitMapToBounds();
   });
  });

</script>
<% end %>

app/views/suggestions/new.html.erb
<div class="container">
  <%= simple_form_for @suggestion do |f| %>
  <%= f.input :title %>
  <%= f.input :content %>
  <%= f.input :content_english %>
  <%= f.input :content_italian %>
  <%= f.input :address %>
  <%= f.input :link %>
  <%= f.input :photo, as: :attachinary %>
  <%= f.button :submit %>
  <% end %>
</div>